dev-version-ext = "pre"
pre-release-commit-message = "(cargo-release) release version {{version}}"
pro-release-commit-message = "(cargo-release) start next development iteration ({{next_version}})"
tag-message = "(cargo-release) `{{crate_name}}` version {{version}}"
sign-commit = true
